using System.Collections.ObjectModel;

namespace StarSyncUniverse.Localization;

/// <summary>
/// Central application UI translation catalog.
///
/// IMPORTANT: This catalog is deliberately restricted to application chrome and UI wording.
/// Star Citizen / game object names, descriptions, factions, services, commodities, locations,
/// source paths and other game-provided content are never translated here.
///
/// Add a new UI term once in <see cref="Entries"/> and use its key from WPF or the WebView renderer.
/// English is the canonical fallback language.
/// </summary>
public static class UiLocalizationCatalog
{
    public const string English = "en";
    public const string German = "de";

    private sealed record Entry(string English, string German);

    private static readonly IReadOnlyDictionary<string, Entry> Entries =
        new ReadOnlyDictionary<string, Entry>(new Dictionary<string, Entry>(StringComparer.Ordinal)
        {
            ["nav.starmap"] = new("Starmap", "Sternenkarte"),
            ["nav.database"] = new("Database", "Datenbank"),
            ["nav.tools"] = new("Tools", "Werkzeuge"),
            ["nav.settings"] = new("Settings", "Einstellungen"),
            ["nav.about"] = new("About", "Über"),
            ["top.search.placeholder"] = new("Search all galaxy objects…", "Alle Galaxieobjekte durchsuchen…"),
            ["top.search.tooltip"] = new("Search all galaxy objects across all loaded systems", "Alle Galaxieobjekte in allen geladenen Systemen durchsuchen"),
            ["top.system"] = new("System:", "System:"),
            ["top.currentData"] = new("CURRENT DATA", "AKTUELLE DATEN"),
            ["top.reloadLive"] = new("Reload LIVE Data.p4k", "LIVE Data.p4k neu laden"),
            ["top.reloadCache"] = new("Reload cached snapshot", "Zwischengespeicherten Stand neu laden"),
            ["status.initializing"] = new("Initializing…", "Initialisierung…"),
            ["status.readingLive"] = new("Reading current LIVE universe data…", "Aktuelle LIVE-Universumsdaten werden gelesen…"),

            ["ui.language"] = new("Language", "Sprache"),
            ["ui.english"] = new("English", "Englisch"),
            ["ui.german"] = new("German", "Deutsch"),
            ["ui.display"] = new("Display", "Anzeige"),
            ["ui.stars"] = new("Stars", "Sterne"),
            ["ui.planetsMoons"] = new("Planets & Moons", "Planeten & Monde"),
            ["ui.stations"] = new("Stations", "Stationen"),
            ["ui.systemStations"] = new("System Stations", "Systemstationen"),
            ["ui.missionStations"] = new("Mission / Event Stations", "Missions- / Eventstationen"),
            ["ui.externalFreightElevator"] = new("External freight elevator", "Externer Frachtaufzug"),
            ["ui.externalFreightElevatorsOnly"] = new("Has external freight elevator", "Mit externem Frachtaufzug"),
            ["ui.orbitalStationFilters"] = new("Orbital station filters", "Raumstationsfilter"),
            ["ui.groundLocationFilters"] = new("Ground location filters", "Bodenlocationsfilter"),
            ["ui.freightElevator"] = new("Freight elevator", "Frachtaufzug"),
            ["ui.surfaceFreightOnly"] = new("Has freight elevator", "Mit Frachtaufzug"),
            ["ui.surfaceVehicleServiceOnly"] = new("Has Vehicle Services", "Mit Vehicle Services"),
            ["ui.surfaceGarageOnly"] = new("Has Garage", "Mit Garage"),
            ["ui.surfaceLandingPadOnly"] = new("Has Landing Pad", "Mit Landing Pad"),
            ["ui.garage"] = new("Garage", "Garage"),
            ["ui.landingPad"] = new("Landing Pad", "Landeplatz"),
            ["ui.shipRefuel"] = new("Ship refuel", "Schiff betanken"),
            ["ui.shipRepair"] = new("Ship repair", "Schiff reparieren"),
            ["ui.surfaceFacilityEvidence"] = new("Facility evidence", "Einrichtungsnachweis"),
            ["ui.freightEvidence"] = new("Freight evidence", "Frachtaufzug-Nachweis"),
            ["ui.freightStatus"] = new("Freight status", "Frachtaufzug-Status"),
            ["ui.yes"] = new("YES", "JA"),
            ["ui.no"] = new("NO", "NEIN"),
            ["ui.notVerified"] = new("NOT VERIFIED", "NICHT VERIFIZIERT"),
            ["ui.racingTracks"] = new("Racing Tracks", "Rennstrecken"),
            ["ui.jumpPoints"] = new("Jump Points", "Sprungpunkte"),
            ["ui.orbits"] = new("Orbits", "Umlaufbahnen"),
            ["ui.asteroidFields"] = new("Asteroid Fields", "Asteroidenfelder"),
            ["ui.labels"] = new("Labels", "Beschriftungen"),
            ["ui.regionBoundaries"] = new("Region Boundaries", "Regionsgrenzen"),
            ["ui.showHidden"] = new("Show Hidden", "Ausgeblendete anzeigen"),
            ["ui.backgroundNebula"] = new("Background Nebula", "Hintergrundnebel"),
            ["ui.all"] = new("All", "Alle"),
            ["ui.highlightMatches"] = new("Highlight matches", "Treffer hervorheben"),
            ["ui.filterMapMatches"] = new("Filter map to matches", "Karte auf Treffer filtern"),
            ["ui.objectParentOrbit"] = new("Object + parent / orbit", "Objekt + Parent / Orbit"),
            ["ui.objectClose"] = new("Object close", "Objekt nah"),
            ["ui.default"] = new("Default", "Standard"),
            ["ui.resetCamera"] = new("Reset camera", "Kamera zurücksetzen"),
            ["ui.dataStatus"] = new("Data status", "Datenstatus"),
            ["ui.planets"] = new("Planets", "Planeten"),
            ["ui.objects"] = new("Objects", "Objekte"),
            ["ui.bodyTargets"] = new("Body targets", "Bodenziele"),
            ["ui.collapseExpandResults"] = new("Collapse / expand results", "Ergebnisse ein-/ausklappen"),
            ["ui.collapseExpandBodyTargets"] = new("Collapse / expand body targets", "Bodenziele ein-/ausklappen"),
            ["ui.bodyLocal3d"] = new("Body-local 3D", "Körperlokal 3D"),
            ["ui.surfaceMap2d"] = new("2D surface map", "2D-Oberflächenkarte"),
            ["ui.openBodyView"] = new("Open body view", "Körperansicht öffnen"),
            ["ui.systemView"] = new("System view", "Systemansicht"),
            ["ui.toggleMenu"] = new("Toggle menu", "Menü ein-/ausblenden"),
            ["ui.toggleDetails"] = new("Toggle details", "Details ein-/ausblenden"),
            ["ui.systemGalaxyTransition"] = new("System / Galaxy transition", "System-/Galaxieansicht wechseln"),
            ["ui.currentLiveSystem"] = new("CURRENT LIVE SYSTEM · AUTHORITATIVE PLACEMENTS", "AKTUELLES LIVE-SYSTEM · AUTORITATIVE POSITIONEN"),
            ["ui.workspace"] = new("Workspace", "Arbeitsbereich"),
            ["ui.selectedObject"] = new("Selected object", "Ausgewähltes Objekt"),
            ["ui.clickObject"] = new("Click an object.", "Objekt anklicken."),
            ["ui.measurementRoute"] = new("Measurement / Route", "Messung / Route"),
            ["ui.rightClickSetRoute"] = new("Right-click an object and set Start / Destination.", "Objekt rechts anklicken und Start / Ziel setzen."),
            ["ui.destination"] = new("Destination", "Ziel"),
            ["ui.searchRoute"] = new("Search all systems, objects, locations…", "Alle Systeme, Objekte und Orte durchsuchen…"),
            ["ui.setDestination"] = new("Set destination", "Ziel setzen"),
            ["ui.calculateRoute"] = new("Calculate Route", "Route berechnen"),
            ["ui.regions"] = new("Regions", "Regionen"),
            ["ui.surfaceLocations"] = new("Surface locations", "Oberflächenorte"),
            ["ui.filterSurfaceLocations"] = new("Filter surface locations…", "Oberflächenorte filtern…"),
            ["ui.selectPlanetMoon"] = new("Select a planet or moon.", "Planet oder Mond auswählen."),
            ["ui.bookmarks"] = new("Bookmarks", "Lesezeichen"),
            ["ui.bookmarkManager"] = new("Bookmark Manager", "Lesezeichenverwaltung"),
            ["ui.share"] = new("Share", "Teilen"),
            ["ui.filterBookmarks"] = new("Filter bookmarks…", "Lesezeichen filtern…"),
            ["ui.noBookmarks"] = new("No bookmarks.", "Keine Lesezeichen."),
            ["ui.saveBookmark"] = new("Save bookmark", "Lesezeichen speichern"),
            ["ui.name"] = new("Name", "Name"),
            ["ui.category"] = new("Category", "Kategorie"),
            ["ui.freeText"] = new("Free text", "Freitext"),
            ["ui.color"] = new("Color", "Farbe"),
            ["ui.showOnMap"] = new("Show on map", "Auf der Karte anzeigen"),
            ["ui.cancel"] = new("Cancel", "Abbrechen"),
            ["ui.save"] = new("Save", "Speichern"),
            ["ui.clear"] = new("Clear", "Leeren"),
            ["ui.mapLegend"] = new("MAP LEGEND", "KARTENLEGENDE"),
            ["ui.station"] = new("Station", "Station"),
            ["ui.planet"] = new("Planet", "Planet"),
            ["ui.moon"] = new("Moon", "Mond"),
            ["ui.star"] = new("Star", "Stern"),
            ["ui.spaceStation"] = new("Space Station", "Raumstation"),
            ["ui.jumpPoint"] = new("Jump Point", "Sprungpunkt"),
            ["ui.orbitLine"] = new("Orbit Line", "Umlaufbahn"),
            ["ui.regionBoundary"] = new("Region Boundary", "Regionsgrenze"),

            ["ctx.setStart"] = new("SET / START", "SETZEN / START"),
            ["ctx.setDestination"] = new("SET / DESTINATION", "SETZEN / ZIEL"),
            ["ctx.bookmarkSave"] = new("BOOKMARK / SAVE", "LESEZEICHEN / SPEICHERN"),
            ["ctx.bookmarkEdit"] = new("BOOKMARK / EDIT", "LESEZEICHEN / BEARBEITEN"),
            ["ctx.bookmarkDelete"] = new("BOOKMARK / DELETE", "LESEZEICHEN / LÖSCHEN"),
            ["ctx.direct"] = new("MODE / DIRECT LINE", "MODUS / DIREKTLINIE"),
            ["ctx.route"] = new("MODE / ROUTE", "MODUS / ROUTE"),
            ["ctx.unsetFocus"] = new("VIEW / UNSET FOCUS", "ANSICHT / FOKUS LÖSEN"),
            ["ctx.clearNav"] = new("NAV / CLEAR", "NAV / LEEREN"),

            ["detail.description"] = new("DESCRIPTION", "BESCHREIBUNG"),
            ["detail.noDescription"] = new("No description is currently available.", "Derzeit ist keine Beschreibung verfügbar."),
            ["detail.addImage"] = new("Add image", "Bild hinzufügen"),
            ["detail.changeImage"] = new("Change image", "Bild ändern"),
            ["detail.deleteImage"] = new("Delete image", "Bild löschen"),
            ["detail.addDescription"] = new("Add / change local description", "Lokale Beschreibung hinzufügen / ändern"),
            ["detail.changeDescription"] = new("Change local description", "Lokale Beschreibung ändern"),
            ["detail.deleteDescription"] = new("Delete local description", "Lokale Beschreibung löschen"),
            ["detail.onlineEnrichment"] = new("Online Enrichment", "Online-Anreicherung"),
            ["detail.servicesCommerce"] = new("Services & Commerce", "Dienste & Handel"),
            ["detail.locationKnowledge"] = new("Location Knowledge", "Ortswissen"),
            ["detail.technicalProvenance"] = new("Technical provenance", "Technische Herkunft"),
            ["detail.sourceStatus"] = new("Source status", "Quellenstatus"),
            ["detail.type"] = new("Type", "Typ"),
            ["detail.parent"] = new("Parent", "Parent"),
            ["detail.jurisdiction"] = new("Jurisdiction", "Jurisdiktion"),
            ["detail.faction"] = new("Faction", "Fraktion"),
            ["detail.factionType"] = new("Faction type", "Fraktionstyp"),
            ["detail.factionRelations"] = new("Faction relations", "Fraktionsbeziehungen"),
            ["detail.services"] = new("Services", "Dienste"),
            ["detail.tradeProduces"] = new("Trade produces", "Handel produziert"),
            ["detail.tradeConsumes"] = new("Trade consumes", "Handel verbraucht"),
            ["detail.correlation"] = new("Correlation", "Korrelation"),
            ["detail.shopRetail"] = new("Shop / retail services", "Shop- / Einzelhandelsdienste"),
            ["detail.tradeTerminal"] = new("Trade terminal services", "Handelsterminal-Dienste"),
            ["detail.tradeProfiles"] = new("Trade profiles", "Handelsprofile"),
            ["detail.commoditiesSold"] = new("Commodities sold here", "Hier verkaufte Waren"),
            ["detail.commoditiesBought"] = new("Commodities bought here", "Hier gekaufte Waren"),
            ["detail.resolvedItemRelations"] = new("Resolved item relations", "Aufgelöste Item-Beziehungen"),
            ["detail.system"] = new("System", "System"),
            ["detail.body"] = new("Body", "Himmelskörper"),
            ["detail.coordinates"] = new("Coordinates", "Koordinaten"),
            ["detail.radiusDiameter"] = new("Radius / diameter", "Radius / Durchmesser"),
            ["detail.rotation"] = new("Rotation", "Rotation"),
            ["detail.placement"] = new("Placement", "Platzierung"),
            ["detail.authority"] = new("Authority", "Autorität"),
            ["detail.class"] = new("Class", "Klasse"),
            ["detail.parentDistance"] = new("Parent distance", "Distanz zum Parent"),
            ["detail.distanceStar"] = new("Distance to star", "Distanz zum Stern"),
            ["detail.elevationStar"] = new("Elevation vs star", "Höhe relativ zum Stern"),
            ["detail.containingVolumes"] = new("Containing volumes", "Enthaltende Volumes"),
            ["detail.radius"] = new("Radius", "Radius"),
            ["detail.rotationPeriod"] = new("Rotation period", "Rotationsperiode"),
            ["detail.rotationAxis"] = new("Rotation axis", "Rotationsachse"),
            ["detail.orbitVisualization"] = new("Orbit visualization", "Orbitdarstellung"),
            ["detail.orbitParent"] = new("Orbit parent", "Orbit-Parent"),
            ["detail.orbitRadius"] = new("Orbit radius", "Orbitradius"),
            ["detail.orbitStatus"] = new("Orbit status", "Orbitstatus"),
            ["detail.qtValid"] = new("QT valid", "QT gültig"),
            ["detail.status"] = new("Status", "Status"),
            ["detail.source"] = new("Source", "Quelle"),
            ["detail.setOrigin"] = new("Set as Origin", "Als Ursprung setzen"),
            ["detail.originSet"] = new("Origin set", "Ursprung gesetzt"),
            ["detail.addBookmark"] = new("Add Bookmark", "Lesezeichen hinzufügen"),
            ["detail.clearOrigin"] = new("Clear Origin", "Ursprung löschen"),
            ["detail.setRouteStart"] = new("Set route start", "Routenstart setzen"),
            ["detail.setRouteDestination"] = new("Set route destination", "Routenziel setzen"),
            ["detail.focus"] = new("Focus", "Fokussieren"),
            ["detail.clearRoute"] = new("Clear route", "Route löschen"),

            ["settings.title"] = new("Settings", "Einstellungen"),
            ["settings.interface"] = new("Interface", "Oberfläche"),
            ["settings.interfaceNote"] = new("UI language affects application controls only. Game object content always remains native.", "Die UI-Sprache betrifft nur Bedienelemente der Anwendung. Spielobjekt-Inhalte bleiben immer nativ."),
            ["settings.apply"] = new("Apply settings", "Einstellungen anwenden"),
            ["settings.starbreaker"] = new("StarBreaker", "StarBreaker"),
            ["settings.scunpacked"] = new("SCUnpacked", "SCUnpacked"),
            ["settings.synhost"] = new("StarSync Sync Host", "StarSync Sync Host"),
            ["settings.integrity"] = new("Integrity & Support", "Integrität & Support"),
            ["settings.runIntegrity"] = new("Run integrity check & create support package", "Integritätsprüfung ausführen & Supportpaket erstellen"),
            ["settings.probeConnection"] = new("Probe connection", "Verbindung prüfen"),
            ["settings.enabled"] = new("Enabled", "Aktiviert"),
            ["settings.path"] = new("Path", "Pfad"),
            ["settings.version"] = new("Version", "Version"),
            ["settings.detected"] = new("Detected", "Erkannt"),
            ["settings.notFound"] = new("NOT FOUND", "NICHT GEFUNDEN"),

            ["workspace.database"] = new("Database", "Datenbank"),
            ["workspace.tools"] = new("Tools", "Werkzeuge"),
            ["workspace.bookmarkManager"] = new("Bookmark Manager", "Lesezeichenverwaltung"),
            ["workspace.groups"] = new("Groups", "Gruppen"),
            ["workspace.multiSelection"] = new("Multi-selection", "Mehrfachauswahl"),
            ["workspace.createGroup"] = new("Create group", "Gruppe erstellen"),
            ["workspace.rename"] = new("Rename", "Umbenennen"),
            ["workspace.deleteGroup"] = new("Delete group", "Gruppe löschen"),
            ["workspace.selectAll"] = new("Select all shown", "Alle sichtbaren auswählen"),
            ["workspace.clearSelection"] = new("Clear", "Auswahl leeren"),
            ["workspace.assign"] = new("Assign", "Zuweisen"),
            ["workspace.move"] = new("Move", "Verschieben"),
            ["workspace.removeGroup"] = new("Remove from group", "Aus Gruppe entfernen"),
            ["workspace.applyCategory"] = new("Apply category", "Kategorie anwenden"),
            ["workspace.showMap"] = new("Show on map", "Auf Karte anzeigen"),
            ["workspace.hideMap"] = new("Hide on map", "Auf Karte ausblenden"),
            ["workspace.deleteSelected"] = new("Delete selected", "Auswahl löschen"),
            ["workspace.publishGroup"] = new("Publish signed group", "Signierte Gruppe veröffentlichen"),
            ["workspace.route"] = new("Route", "Route"),
            ["workspace.start"] = new("Start", "Start"),
            ["workspace.mode"] = new("Mode", "Modus"),
            ["workspace.coordinateTools"] = new("Coordinate tools", "Koordinatenwerkzeuge"),
            ["workspace.openBookmarks"] = new("Open bookmark panel", "Lesezeichen öffnen"),

            ["about.title"] = new("About", "Über"),
            ["about.quickStart"] = new("Quick Start & Operation", "Schnellstart & Bedienung"),
            ["about.dataSources"] = new("Configure data sources", "Datenquellen einrichten"),
            ["about.syncHost"] = new("Connect SyncHost", "SyncHost anbinden"),
            ["about.integrity"] = new("Integrity Check & Support Package", "Integritätsprüfung & Supportpaket"),
            ["about.currentStatus"] = new("Current data status", "Aktueller Datenstatus"),

            ["settings.visibility"] = new("Visibility", "Sichtbarkeit"),
            ["settings.optionalAdapters"] = new("Optional data-source adapters", "Optionale Datenquellen-Adapter"),
            ["settings.localP4k"] = new("Local Data.p4k / StarBreaker", "Lokale Data.p4k / StarBreaker"),
            ["settings.enableLocalP4k"] = new("Enable local Data.p4k update adapter", "Lokalen Data.p4k-Update-Adapter aktivieren"),
            ["settings.detectionVersion"] = new("Detection / version", "Erkennung / Version"),
            ["settings.starbreakerPath"] = new("StarBreaker path", "StarBreaker-Pfad"),
            ["settings.dataP4kPath"] = new("Data.p4k path", "Data.p4k-Pfad"),
            ["settings.scImport"] = new("SCUnpacked data import", "SCUnpacked-Datenimport"),
            ["settings.enableSc"] = new("Enable local SCUnpacked enrichment", "Lokale SCUnpacked-Anreicherung aktivieren"),
            ["settings.scRoot"] = new("SCUnpacked root", "SCUnpacked-Root"),
            ["settings.onlineApi"] = new("Online API enrichment", "Online-API-Anreicherung"),
            ["settings.provider"] = new("Provider", "Anbieter"),
            ["settings.consent"] = new("I consent to external HTTP requests", "Ich stimme externen HTTP-Anfragen zu"),
            ["settings.enableOnline"] = new("Enable online location enrichment", "Online-Ortsanreicherung aktivieren"),
            ["settings.clearOnlineCache"] = new("Clear online enrichment cache", "Online-Anreicherungscache leeren"),
            ["settings.enableSyncHost"] = new("Enable SyncHost connection", "SyncHost-Verbindung aktivieren"),
            ["settings.syncBaseUrl"] = new("SyncHost base URL", "SyncHost-Basis-URL"),
            ["settings.transport"] = new("Transport", "Transport"),
            ["settings.playerHandle"] = new("Player / handle", "Spieler / Handle"),
            ["settings.organization"] = new("Organization", "Organisation"),
            ["settings.clientId"] = new("Client ID", "Client-ID"),
            ["settings.fingerprint"] = new("Fingerprint", "Fingerabdruck"),
            ["settings.signature"] = new("Signature", "Signatur"),
            ["settings.saveSyncHost"] = new("Save SyncHost settings", "SyncHost-Einstellungen speichern"),
            ["settings.renderer"] = new("Renderer", "Renderer"),
            ["settings.bodyTextures"] = new("Body texture entries", "Körpertextur-Einträge"),
            ["settings.camera"] = new("Camera", "Kamera"),
            ["settings.illustrated"] = new("Illustrated system overview", "Illustrierte Systemübersicht"),
            ["settings.showLegend"] = new("Show bottom map legend", "Kartenlegende unten anzeigen"),
            ["settings.smoothTravel"] = new("Smooth focus travel", "Sanfte Fokusfahrt"),
            ["settings.travelSpeed"] = new("Focus travel speed", "Fokusfahrt-Geschwindigkeit"),
            ["settings.fast"] = new("Fast - 0.5 s", "Schnell - 0,5 s"),
            ["settings.normal"] = new("Normal - 1.0 s", "Normal - 1,0 s"),
            ["settings.slow"] = new("Slow - 1.6 s", "Langsam - 1,6 s"),
            ["settings.cinematic"] = new("Cinematic - 2.4 s", "Filmisch - 2,4 s"),
            ["settings.verySlow"] = new("Very slow - 3.5 s", "Sehr langsam - 3,5 s"),
            ["settings.applySources"] = new("Apply data-source settings", "Datenquellen-Einstellungen anwenden"),
            ["settings.saveReloadSources"] = new("Save & reload data sources", "Datenquellen speichern & neu laden"),
            ["settings.notRun"] = new("Not run.", "Nicht ausgeführt."),
            ["settings.active"] = new("ACTIVE", "AKTIV"),
            ["settings.fallback"] = new("FALLBACK", "FALLBACK"),
            ["settings.off"] = new("OFF", "AUS"),
            ["settings.configured"] = new("CONFIGURED / probe not run", "KONFIGURIERT / Prüfung nicht ausgeführt"),

            ["ui.affiliation"] = new("Affiliation", "Zugehörigkeit"),
            ["ui.size"] = new("Size", "Größe"),
            ["ui.starType"] = new("Star type", "Sterntyp"),
            ["ui.entities"] = new("Entities", "Entitäten"),
            ["ui.physicalBodies"] = new("Physical bodies", "Physische Himmelskörper"),
            ["ui.bodyLocalTargets"] = new("Body-local targets", "Körperlokale Ziele"),
            ["ui.dataAuthority"] = new("Data authority", "Datenautorität"),
            ["ui.installation"] = new("Installation", "Installation"),
            ["ui.configuration"] = new("Configuration", "Konfiguration"),
            ["ui.dataSources"] = new("Data sources", "Datenquellen"),
            ["ui.support"] = new("Support", "Support"),
            ["ui.navigation"] = new("Navigation", "Navigation"),
            ["ui.views"] = new("Views", "Ansichten"),
            ["ui.map"] = new("Map", "Karte"),
            ["ui.found"] = new("FOUND", "GEFUNDEN"),
            ["ui.notConfigured"] = new("NOT CONFIGURED", "NICHT KONFIGURIERT"),
            ["ui.error"] = new("ERROR", "FEHLER"),
            ["ui.missing"] = new("MISSING", "FEHLT"),
            ["ui.ok"] = new("OK", "OK"),
            ["ui.source"] = new("SOURCE", "QUELLE"),
            ["ui.checked"] = new("checked", "geprüft"),
            ["ui.system"] = new("SYSTEM", "SYSTEM"),
            ["ui.authoritativePositions"] = new("AUTHORITATIVE POSITIONS", "AUTORITATIVE POSITIONEN"),
            ["ui.galaxy"] = new("GALAXY", "GALAXIE"),
            ["ui.topology"] = new("TOPOLOGY · NO INTERSTELLAR METRIC", "TOPOLOGIE · KEINE INTERSTELLARE METRIK"),
            ["ui.expandResults"] = new("Expand results", "Ergebnisse ausklappen"),
            ["ui.collapseResults"] = new("Collapse results", "Ergebnisse einklappen"),
            ["ui.focus"] = new("Focus", "Fokussieren"),
            ["ui.edit"] = new("Edit", "Bearbeiten"),
            ["ui.delete"] = new("Delete", "Löschen"),
            ["ui.noMatchingBookmarks"] = new("No matching bookmarks.", "Keine passenden Lesezeichen."),
            ["ui.noMatchingSurface"] = new("No matching surface locations.", "Keine passenden Oberflächenorte."),
            ["ui.noSurfaceLocations"] = new("No CURRENT LIVE surface locations.", "Keine CURRENT-LIVE-Oberflächenorte."),

            ["note.settingsSubtitle"] = new("Renderer, visibility and optional data sources", "Renderer, Sichtbarkeit und optionale Datenquellen"),
            ["note.optionalAdapters"] = new("StarSyncUniverse always uses the packaged body-presentation textures. The adapters below only refresh world data or enrich metadata; disabling them never disables planet/moon textures.", "StarSyncUniverse verwendet immer die paketierten Darstellungstexturen der Himmelskörper. Die folgenden Adapter aktualisieren nur Weltdaten oder ergänzen Metadaten; ihr Deaktivieren schaltet Planeten-/Mondtexturen niemals ab."),
            ["note.starbreakerInstall"] = new("Preferred installation: copy starbreaker.exe into the StarSyncUniverse application directory (a direct child or subdirectory is auto-detected). If no executable is found, configure its full path below. When enabled, StarSyncUniverse invokes StarBreaker against the configured Star Citizen LIVE Data.p4k, rebuilds authoritative placement/object data and refreshes presentation caches. After a Star Citizen update, the next reload reads the updated Data.p4k again; if the game data format requires a newer StarBreaker, replace starbreaker.exe and reload.", "Empfohlene Installation: starbreaker.exe in das StarSyncUniverse-Programmverzeichnis oder einen Unterordner kopieren; die Datei wird dort automatisch erkannt. Wird keine EXE gefunden, den vollständigen Pfad unten angeben. Bei Aktivierung verwendet StarSyncUniverse StarBreaker mit der konfigurierten Star-Citizen-LIVE-Data.p4k, baut autoritative Placement-/Objektdaten neu auf und aktualisiert Darstellungscaches. Nach einem Star-Citizen-Update wird beim nächsten Reload die aktualisierte Data.p4k erneut gelesen; verlangt das neue Datenformat eine neuere StarBreaker-Version, starbreaker.exe ersetzen und neu laden."),
            ["note.scInstall"] = new("Preferred installation: download/copy the SCUnpacked data folder below StarSyncUniverse/database. StarSyncUniverse searches that directory recursively for starmap_positions.json and uses the containing folder automatically. If no dataset is found, configure its root path below. When enabled, SCUnpacked refreshes readable names, descriptions, factions, services, trade/location semantics and related metadata; it does not replace LIVE geometry or packaged body textures. After a Star Citizen/SCUnpacked update, replace the dataset in /database (or update the configured folder) and use Save & reload data sources so the semantic database is rebuilt from the newer snapshot.", "Empfohlene Installation: den SCUnpacked-Datenordner nach StarSyncUniverse/database kopieren. StarSyncUniverse sucht dieses Verzeichnis rekursiv nach starmap_positions.json und verwendet den enthaltenden Ordner automatisch. Wird kein Datensatz gefunden, den Root-Pfad unten angeben. Bei Aktivierung aktualisiert SCUnpacked lesbare Namen, Beschreibungen, Fraktionen, Dienste, Handels-/Ortssemantik und verwandte Metadaten; LIVE-Geometrie oder paketierte Himmelskörpertexturen werden nicht ersetzt. Nach einem Star-Citizen-/SCUnpacked-Update den Datensatz in /database ersetzen (oder den konfigurierten Ordner aktualisieren) und Datenquellen speichern & neu laden, damit die semantische Datenbank aus dem neuen Snapshot aufgebaut wird."),
            ["note.onlineConsent"] = new("Consent is required before any external enrichment request is sent. When enabled, StarSyncUniverse may refresh location descriptions/details and cache available images from the configured external provider. Normal web-request metadata, including the public IP address, can be visible to that provider. The packaged location baseline remains fully usable without this option.", "Vor jeder externen Anreicherungsanfrage ist eine ausdrückliche Zustimmung erforderlich. Bei Aktivierung kann StarSyncUniverse Ortsbeschreibungen/-details aktualisieren und verfügbare Bilder des konfigurierten externen Anbieters zwischenspeichern. Übliche Web-Request-Metadaten einschließlich der öffentlichen IP-Adresse können für diesen Anbieter sichtbar sein. Die paketierte Orts-Baseline bleibt auch ohne diese Option vollständig nutzbar."),
            ["note.syncHost"] = new("Configure the complete public SyncHost base URL (scheme, host, port and API base path), then enter the Star Citizen player handle and optional organization. StarSyncUniverse creates a persistent Client ID and ECDSA-P256/SHA-256 identity; the private key remains DPAPI-protected on this Windows account. Probe connection first requests sync/sync-host-manifest.json and then sends a signed request to api/v1/clients/me?clientId=.... A successful probe requires both the manifest and an authorized/known client registry response.", "Die vollständige öffentliche SyncHost-Basis-URL konfigurieren (Schema, Host, Port und API-Basispfad), danach Star-Citizen-Spielerhandle und optional Organisation eintragen. StarSyncUniverse erzeugt eine persistente Client-ID und ECDSA-P256/SHA-256-Identität; der private Schlüssel bleibt auf diesem Windows-Konto DPAPI-geschützt. Verbindung prüfen ruft zuerst sync/sync-host-manifest.json ab und sendet danach eine signierte Anfrage an api/v1/clients/me?clientId=.... Eine erfolgreiche Prüfung benötigt sowohl das Manifest als auch eine autorisierte/bekannte Client-Registry-Antwort."),
            ["note.renderer"] = new("Body textures are demand-loaded and retained in a bounded GPU/image LRU. Cloud and normal maps remain LOD-lazy.", "Himmelskörpertexturen werden bei Bedarf geladen und in einem begrenzten GPU-/Bild-LRU gehalten. Wolken- und Normal-Maps bleiben LOD-lazy."),
            ["note.camera"] = new("Presentation-only: moons, stations and local orbit cues remain readable in the zoomed-out system view and blend continuously back to true projected spacing while zooming in.", "Nur Darstellung: Monde, Stationen und lokale Orbit-Hinweise bleiben in der herausgezoomten Systemansicht lesbar und gehen beim Hineinzoomen kontinuierlich in die echte projizierte Distanz über."),
            ["note.applySources"] = new("Changing the Data.p4k adapter or SCUnpacked source reloads the universe dataset. Online access remains separately gated by explicit consent.", "Eine Änderung des Data.p4k-Adapters oder der SCUnpacked-Quelle lädt den Universumsdatensatz neu. Online-Zugriff bleibt separat durch ausdrückliche Zustimmung geschützt."),
            ["note.integrity"] = new("Runs a read-only validation of the StarSyncUniverse installation, required StarBreaker commands, Data.p4k access, SCUnpacked structure/content and the configured SyncHost connection. The result is written as a log and a ZIP support package. Private SyncHost key material, bookmarks and raw game/database payloads are never included.", "Führt eine schreibgeschützte Validierung der StarSyncUniverse-Installation, der benötigten StarBreaker-Kommandos, des Data.p4k-Zugriffs, der SCUnpacked-Struktur/-Inhalte und der konfigurierten SyncHost-Verbindung durch. Das Ergebnis wird als Log und ZIP-Supportpaket gespeichert. Private SyncHost-Schlüssel, Lesezeichen sowie rohe Spiel-/Datenbankdaten werden niemals aufgenommen."),

            ["ui.distance3d"] = new("3D distance", "3D-Distanz"),
            ["ui.altitude"] = new("Altitude", "Höhe"),
            ["ui.atmosphere"] = new("Atmosphere", "Atmosphäre"),
            ["ui.axisLatLon"] = new("Axis lat/lon", "Achsen-Breite/Länge"),
            ["ui.azimuthElevation"] = new("Azimuth / elevation", "Azimut / Elevation"),
            ["ui.boundsRadius"] = new("Bounds radius", "Begrenzungsradius"),
            ["ui.buildVersion"] = new("Build Version", "Build-Version"),
            ["ui.citiesLandingZones"] = new("Cities / landing zones", "Städte / Landezonen"),
            ["ui.coordinateStatus"] = new("Coordinate status", "Koordinatenstatus"),
            ["ui.directDistance"] = new("Direct distance", "Direkte Distanz"),
            ["ui.interstellarTransits"] = new("Interstellar transits", "Interstellare Übergänge"),
            ["ui.knownLocations"] = new("Known locations", "Bekannte Orte"),
            ["ui.length"] = new("Length", "Länge"),
            ["ui.liveP4k"] = new("LIVE Data (p4k)", "LIVE-Daten (p4k)"),
            ["ui.liveDataP4k"] = new("LIVE DATA · Data.p4k", "LIVE-DATEN · Data.p4k"),
            ["ui.mapProjection"] = new("Map projection", "Kartenprojektion"),
            ["ui.measureFrom"] = new("Measure from", "Messen ab"),
            ["ui.moons"] = new("Moons", "Monde"),
            ["ui.operator"] = new("Operator", "Betreiber"),
            ["ui.other"] = new("Other", "Sonstige"),
            ["ui.outposts"] = new("Outposts", "Außenposten"),
            ["ui.population"] = new("Population", "Bevölkerung"),
            ["ui.scope"] = new("Scope", "Bereich"),
            ["ui.semanticSource"] = new("Semantic source", "Semantische Quelle"),
            ["ui.segments"] = new("Segments", "Segmente"),
            ["ui.totalDistance"] = new("Total distance", "Gesamtdistanz"),
            ["ui.unavailableFrames"] = new("Unavailable for independent coordinate frames", "Für unabhängige Koordinatenrahmen nicht verfügbar"),
            ["ui.universeMap"] = new("Universe Map", "Universumskarte"),
            ["ui.visualClass"] = new("Visual class", "Visuelle Klasse"),
            ["ui.stellarObjects"] = new("Stellar Objects", "Stellare Objekte"),
            ["ui.objectsLoaded"] = new("Objects Loaded", "Geladene Objekte"),
            ["ui.dataSource"] = new("Data Source", "Datenquelle"),
            ["ui.features"] = new("Features", "Merkmale"),
            ["ui.calculating"] = new("Calculating…", "Berechnung…"),
            ["ui.noImage"] = new("NO IMAGE", "KEIN BILD"),
            ["ui.newGroupName"] = new("New group name", "Neuer Gruppenname"),
            ["ui.searchDatabase"] = new("Search location, description, faction, service, trade…", "Ort, Beschreibung, Fraktion, Dienst oder Handel durchsuchen…"),
            ["ui.searchTechnical"] = new("Search name, UUID, class, source…", "Name, UUID, Klasse oder Quelle durchsuchen…"),
            ["ui.autoDiscoverDatabase"] = new("Auto-discover latest below /database", "Neueste Version unter /database automatisch erkennen"),
            ["ui.sourceStatusTitle"] = new("Source status", "Quellenstatus"),
            ["ui.rsiLive"] = new("RSI LIVE", "RSI LIVE"),
            ["ui.simulatedCircular"] = new("SIMULATED CIRCULAR", "SIMULIERT KREISFÖRMIG"),
            ["ui.webgl2"] = new("WebGL2", "WebGL2"),
            ["ui.zoom"] = new("ZOOM", "ZOOM"),
            ["ui.bodyLocalX"] = new("Body-local X", "Körperlokal X"),
            ["ui.bodyLocalY"] = new("Body-local Y", "Körperlokal Y"),
            ["ui.bodyLocalZ"] = new("Body-local Z", "Körperlokal Z"),
            ["ui.thickness"] = new("Thickness", "Dicke"),
            ["ui.deleteDescription"] = new("Delete description", "Beschreibung löschen"),
            ["ui.scEnrichment"] = new("SCUnpacked enrichment", "SCUnpacked-Anreicherung"),

            ["status.locatingSc"] = new("Locating optional SCUnpacked refresh/enrichment data…", "Optionale SCUnpacked-Aktualisierungs-/Anreicherungsdaten werden gesucht…"),
            ["status.refreshingKnowledge"] = new("Refreshing packaged location knowledge from optional SCUnpacked data…", "Paketiertes Ortswissen wird aus optionalen SCUnpacked-Daten aktualisiert…"),
            ["status.refreshingTextures"] = new("Refreshing body presentation textures for", "Darstellungstexturen werden aktualisiert für"),
            ["status.archivingTextures"] = new("Archiving local original/updated body textures for", "Lokale Original-/aktualisierte Himmelskörpertexturen werden archiviert für"),
            ["status.cachedSnapshots"] = new("Local Data.p4k update adapter disabled · loading cached universe snapshots…", "Lokaler Data.p4k-Update-Adapter deaktiviert · zwischengespeicherte Universumsstände werden geladen…"),
            ["status.preloadingViewer"] = new("Building and preloading technical universe viewer…", "Technische Universumsansicht wird erstellt und vorgeladen…"),
            ["status.loadFailed"] = new("Universe load failed:", "Laden des Universums fehlgeschlagen:"),
            ["status.onlineActive"] = new("ACTIVE - external requests allowed by user consent", "AKTIV - externe Anfragen durch Nutzerzustimmung erlaubt"),
            ["status.onlineOff"] = new("OFF - no external enrichment requests", "AUS - keine externen Anreicherungsanfragen"),
            ["status.cacheClearRequested"] = new("Cache clear requested.", "Cache-Löschung angefordert."),
            ["status.settingsSaved"] = new("Settings saved locally.", "Einstellungen lokal gespeichert."),
            ["status.probingSync"] = new("Probing signed SyncHost connection...", "Signierte SyncHost-Verbindung wird geprüft..."),
            ["status.runningIntegrity"] = new("Running integrity check...", "Integritätsprüfung läuft..."),
            ["status.validatingSupport"] = new("Saving current settings and validating Tool / StarBreaker / SCUnpacked / SyncHost...", "Aktuelle Einstellungen werden gespeichert und Tool / StarBreaker / SCUnpacked / SyncHost validiert..."),
            ["status.onlineConsentRequired"] = new("Online enrichment requires consent.", "Online-Anreicherung erfordert Zustimmung."),
            ["status.saving"] = new("Saving...", "Speichern..."),
            ["status.savingReload"] = new("Saving settings and reloading data sources...", "Einstellungen werden gespeichert und Datenquellen neu geladen..."),
            ["status.connected"] = new("CONNECTED", "VERBUNDEN"),
            ["status.notReady"] = new("NOT READY", "NICHT BEREIT"),
            ["status.found"] = new("FOUND", "GEFUNDEN"),
            ["status.detected"] = new("DETECTED", "ERKANNT"),
            ["status.notFoundPath"] = new("NOT FOUND · path required", "NICHT GEFUNDEN · Pfad erforderlich"),
            ["status.configuredProbe"] = new("CONFIGURED / probe not run", "KONFIGURIERT / Prüfung nicht ausgeführt"),
            ["status.rendererActive"] = new("ACTIVE", "AKTIV"),
            ["status.rendererFallback"] = new("FALLBACK", "FALLBACK"),

            ["workspace.allBookmarks"] = new("All local bookmarks", "Alle lokalen Lesezeichen"),
            ["workspace.noGroups"] = new("No groups yet", "Noch keine Gruppen"),
            ["workspace.creator"] = new("Creator", "Ersteller"),
            ["workspace.location"] = new("Location", "Ort"),
            ["workspace.trade"] = new("Trade", "Handel"),
            ["workspace.factionJurisdiction"] = new("Faction / Jurisdiction", "Fraktion / Jurisdiktion"),
            ["workspace.idFingerprint"] = new("ID / fingerprint", "ID / Fingerabdruck"),
            ["workspace.groupName"] = new("Group name", "Gruppenname"),
            ["workspace.noResolvedPlanets"] = new("No resolved planets.", "Keine aufgelösten Planeten."),
            ["workspace.noObjectSelected"] = new("No object selected.", "Kein Objekt ausgewählt."),
            ["workspace.clickBodyTarget"] = new("Click a body-local target.", "Körperlokales Ziel anklicken."),
            ["workspace.noBodyDefinition"] = new("No CURRENT LIVE body definition", "Keine CURRENT-LIVE-Himmelskörperdefinition"),
        });

    public static string NormalizeLanguage(string? language) =>
        string.Equals(language, German, StringComparison.OrdinalIgnoreCase) ? German : English;

    public static string T(string? language, string key)
    {
        if (!Entries.TryGetValue(key, out var entry)) return key;
        return NormalizeLanguage(language) == German ? entry.German : entry.English;
    }

    /// <summary>
    /// Returns an English-source to translated-string map for safe WebView localization.
    /// Only exact UI strings from this catalog are replaced; arbitrary/game-provided strings are untouched.
    /// </summary>
    public static IReadOnlyDictionary<string, string> BuildExactTextMap(string? language)
    {
        var useGerman = NormalizeLanguage(language) == German;
        var result = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (var entry in Entries.Values)
        {
            var translated = useGerman ? entry.German : entry.English;
            result[entry.English] = translated;
            result[entry.German] = translated;
        }
        return result;
    }

    public static IReadOnlyDictionary<string, string> BuildKeyMap(string? language)
    {
        var useGerman = NormalizeLanguage(language) == German;
        return Entries.ToDictionary(x => x.Key, x => useGerman ? x.Value.German : x.Value.English, StringComparer.Ordinal);
    }
}
